[package]
name = "anime-launcher-sdk"
version = "0.1.0"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
edition = "2021"

[dependencies]
anime-game-core = { path = "anime-game-core", features = ["genshin", "all", "static"] }

anyhow = "1.0"
dirs = "4.0.0"
tracing = "0.1"

serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
enum-ordinalize = { version = "3.1", optional = true }

wincompatlib = { version = "0.2", optional = true }
lazy_static = { version = "1.4", optional = true }
md5 = { version = "0.7", optional = true }

[features]
states = []
config = ["dep:serde", "dep:serde_json", "dep:enum-ordinalize"]
components = ["dep:wincompatlib", "dep:lazy_static"]
game = ["components", "config"]
fps-unlocker = ["dep:md5"]

default = ["all"]
all = ["states", "config", "components", "game", "fps-unlocker"]
