[package]
name = "anime-launcher-sdk"
version = "0.3.1"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
edition = "2021"
build = "build.rs"

[dependencies]
anime-game-core = { path = "anime-game-core", features = ["genshin", "all", "static"] }

anyhow = "1.0"
dirs = "4.0.0"
tracing = "0.1"

serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
enum-ordinalize = { version = "3.1", optional = true }

wincompatlib = { version = "0.2", optional = true }
lazy_static = { version = "1.4", optional = true }
md-5 = { version = "0.10", features = ["asm"], optional = true }
discord-rich-presence = { version = "0.2.3", optional = true }

[features]
states = []
config = ["dep:serde", "dep:serde_json", "dep:enum-ordinalize"]
components = ["dep:wincompatlib", "dep:lazy_static"]
game = ["components", "config"]
fps-unlocker = ["dep:md-5"]
discord-rpc = ["dep:discord-rich-presence"]

default = ["all"]
all = ["states", "config", "components", "game", "fps-unlocker", "discord-rpc"]
